import 'dart:convert';

import 'package:drift/drift.dart' show Variable;
import 'package:planit_mobile/core/database/app_database.dart';
import 'package:planit_mobile/core/money/money.dart';
import 'package:planit_mobile/features/accounts/data/accounts_local_data_source.dart';
import 'package:planit_mobile/features/offline_finance/data/offline_finance_store.dart';
import 'package:planit_mobile/features/offline_finance/domain/offline_finance.dart';
import 'package:planit_mobile/features/settings/data/privacy_api.dart';
import 'package:planit_mobile/features/transactions/data/transactions_local_data_source.dart';
import 'package:planit_mobile/features/transactions/domain/transaction.dart';

/// Exports always read the signed-in owner's database, including unsent work.
/// CSV cells are quoted and untrusted text is protected against spreadsheet formulas.
final class LocalDataExport {
  const LocalDataExport(this.database);
  final AppDatabase database;

  Future<PrivacyDownload> transactions(String ownerId) =>
      database.transaction(() async {
        final transactions = await TransactionsLocalDataSource(
          database,
        ).watch(ownerId).first;
        final accounts = {
          for (final row in await database.readAccounts(ownerId))
            row.id: row.name,
        };
        final categories = {
          for (final row in await database.watchCategories(ownerId).first)
            row.id: row.name,
        };
        return _csv(
          'transactions',
          [
            [
              'id',
              'occurred_at_utc',
              'account',
              'type',
              'amount',
              'currency',
              'status',
              'category',
              'counterparty',
              'note',
              'sync_state',
              'pending_action',
            ],
            for (final row in transactions)
              [
                row.id,
                row.occurredAt.toUtc().toIso8601String(),
                accounts[row.accountId] ?? row.accountId,
                row.type.apiValue,
                row.amount.toApiString(),
                row.amount.currency,
                row.status.name.toUpperCase(),
                categories[row.categoryId] ?? row.categoryId ?? '',
                row.counterparty ?? '',
                row.note ?? '',
                row.syncState.name.toUpperCase(),
                row.pendingAction ?? '',
              ],
          ],
          numericColumns: {4},
        );
      });

  Future<PrivacyDownload> accounts(String ownerId) =>
      database.transaction(() async {
        final accounts = await AccountsLocalDataSource(database).read(ownerId);
        final rows = await TransactionsLocalDataSource(
          database,
        ).watch(ownerId).first;
        final pending = buildPendingAccountBalances(rows);
        return _csv(
          'balances',
          [
            [
              'id',
              'account',
              'currency',
              'saved_balance',
              'pending_delta',
              'estimated_balance',
              'balance_as_of_utc',
              'status',
            ],
            for (final account in accounts)
              [
                account.id,
                account.name,
                account.currency,
                account.calculatedBalance.toApiString(),
                (pending[account.id]?.delta ?? Money.zero(account.currency))
                    .toApiString(),
                (account.calculatedBalance +
                        (pending[account.id]?.delta ??
                            Money.zero(account.currency)))
                    .toApiString(),
                account.balanceAsOf.toUtc().toIso8601String(),
                account.status.name.toUpperCase(),
              ],
          ],
          numericColumns: {3, 4, 5},
        );
      });

  /// Recovery archive, deliberately distinct from the server's portable restore
  /// format. Includes the durable queue; excludes authentication and receipt bytes.
  Future<PrivacyDownload> archive(
    String ownerId,
    OfflineFinanceStore store,
  ) async {
    final budgets = await store.readBudgets(ownerId);
    final templates = await store.readTemplates(ownerId);
    return database.transaction(() async {
      final tables = <String, Object?>{};
      for (final table in database.allTables) {
        if (table == database.localWalletSnapshots) continue;
        // Table names are generated by Drift, never taken from input.
        final rows = await database
            .customSelect(
              'SELECT * FROM "${table.actualTableName}" WHERE owner_id = ?',
              variables: [Variable<String>(ownerId)],
            )
            .get();
        tables[table.actualTableName] = rows.map((row) => row.data).toList();
      }
      return PrivacyDownload(
        filename: _filename('device-archive', 'json'),
        bytes: utf8.encode(
          const JsonEncoder.withIndent('  ').convert({
            'format': 'planit-device-recovery-archive',
            'version': 1,
            'database_schema': database.schemaVersion,
            'owner_id': ownerId,
            'created_at': DateTime.now().toUtc().toIso8601String(),
            'notice':
                'Contains private financial data and pending operations. No passwords, session tokens or receipt images. This recovery archive is not accepted by server portable restore.',
            'tables': tables,
            'budgets': budgets.map((b) => b.toJson()).toList(),
            'templates': templates.map((t) => t.toJson()).toList(),
          }),
        ),
      );
    });
  }

  PrivacyDownload _csv(
    String name,
    List<List<String>> rows, {
    required Set<int> numericColumns,
  }) {
    final text = StringBuffer('\uFEFF');
    for (var rowIndex = 0; rowIndex < rows.length; rowIndex++) {
      final row = rows[rowIndex];
      text.writeln(
        List.generate(
          row.length,
          (index) => csvCell(
            row[index],
            numeric: rowIndex > 0 && numericColumns.contains(index),
          ),
        ).join(','),
      );
    }
    return PrivacyDownload(
      filename: _filename(name, 'csv'),
      bytes: utf8.encode(text.toString()),
    );
  }

  String _filename(String name, String extension) =>
      'planit-phone-$name-${DateTime.now().toUtc().toIso8601String().replaceAll(':', '-')}.$extension';
}

String csvCell(String value, {bool numeric = false}) {
  final safe =
      !numeric &&
          (RegExp(r'^\s*[=+@-]').hasMatch(value) ||
              value.startsWith('\t') ||
              value.startsWith('\r'))
      ? "'$value"
      : value;
  return '"${safe.replaceAll('"', '""')}"';
}
